name: LastFM Music Chart Discord Webhook

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Running Script
        env:
          WEBHOOK_URL: ${{ secrets.LASTFM_MUSIC_CHART }}
        run: |
          pip install -r requirements.txt
          python lastfm_daily_chart.py